### ISSUE TITLE
regorust vs regorus

### ISSUE THREAD

**Issue by cosmincatalin** [microsoft/rego-cpp#99]
Not an issue, per say, but what is the difference between `regorust` and `regorus`? I'm interested in this especially in the context of both projects being under the `microsoft` organisation.

**Comment by mjp41** [comment]
Do you mean a comparison between `regorus` and `rego-cpp`?

Related question, https://github.com/microsoft/regorus/issues/113

**Comment by matajoh** [comment]
Great question! There are a few differences, which I'll do my best to highlight. Our project (`rego-cpp`) is primarily a C++ implementation of the Rego language compiler and runtime, for use and inclusion in C++ projects. Our goal is to be fully compatible with all aspects of the Rego language, which is why we've prioritized compatibility with their test suite. We also are very keen to reduce the TCB and as such have implemented (almost) everything internally instead of via third-party packages. Because the project is implemented in C++, it is fairly straightforward to add wrappers for other languages, including Rust, which is why we have done so. The main features of this project are:

1. `rego-cpp` is a cross-platform C++ implementation
2. We release and maintain thin wrappers for other languages (C, Python, and Rust at time of writing) via FFI
3. We explicitly import and run the OPA test suite in order to maintain compatibility with the language
4. We perform extensive fuzzing and testing on the compiler itself
5. `rego-cpp` is certainly fast enough to be used as a drop-in replacement for OPA in most circumstances, but performance has not been a core concern of the project so far. Once we reach full compatibility (some of the builtins  are still being worked on) we will turn our focus to optimizing execution speed. However, `regorus` will almost certainly always be faster than our Rust wrapper due to being a native Rust implementation.
6. `rego-cpp` is extensible, with it being straightforward to write custom builtins in C++ (and eventually in other languages).

I hope this clears this up a bit! Basically TLDR `regorus` is a native Rust implementation, `regorust` is the Rust wrapper of the `rego-cpp` project.

**Comment by cosmincatalin** [comment]
Hi @matajoh , thank you for detailed response. I think it's clear now.
I wish you success with it, and personally I am looking forward to use it.
